# Generated by Django 4.1.4 on 2023-06-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mychatapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mychatapp.profile",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(
                null=True, related_name="my_friends", to="mychatapp.friend"
            ),
        ),
    ]
