# Generated by Django 4.1.4 on 2023-06-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mychatapp", "0002_friend_profile_profile_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="profile",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mychatapp.profile",
            ),
        ),
    ]
